name: AnarchyExploitFixes
version: ${project.version}
main: me.moomoo.anarchyexploitfixes.AnarchyExploitFixes
authors: [ moo, xGinko ]
description: ${project.description}
softdepend: [ ProtocolLib ]
api-version: '1.19'
folia-supported: true
website: ${project.url}
commands:
  aef:
    usage: /aef [ reload, version, elytra, geared, lag ]
    description: AnarchyExploitFixes admin commands
  toggleconnectionmsgs:
    usage: /toggleconnectionmsgs
    description: Toggle connection messages
  say:
    usage: /say broadcast message
    description: Broadcast a message using your own prefix and format
  help:
    usage: /help
    description: Shows a customizable help message to players
permissions:
  anarchyexploitfixes.*:
    description: Admin plugin permissions
    children:
      anarchyexploitfixes.commandwhitelistbypass: true
      anarchyexploitfixes.chatbypass: true
      anarchyexploitfixes.netherroofbypass: true
      anarchyexploitfixes.cmd.*: true
  anarchyexploitfixes.chatbypass:
    description: Bypass chat restrictions if enabled
  anarchyexploitfixes.netherroofbypass:
    description: Bypass nether roof restrictions if enabled
  anarchyexploitfixes.mapspambypass:
    description: Bypass map creation restrictions if enabled
  anarchyexploitfixes.silentJoin:
    description: enable silent join mode
  anarchyexploitfixes.silentLeave:
    description: enable silent join mode
  anarchyexploitfixes.commandwhitelistbypass:
    description: Bypass command whitelist if enabled
  anarchyexploitfixes.cmd.*:
    description: All plugin command permissions
    children:
      anarchyexploitfixes.cmd.version: true
      anarchyexploitfixes.cmd.reload: true
      anarchyexploitfixes.cmd.lag: true
      anarchyexploitfixes.cmd.geared: true
      anarchyexploitfixes.cmd.kickphrase: true
      anarchyexploitfixes.cmd.elytra: true
      anarchyexploitfixes.cmd.toggleconnectionmsgs: true
      anarchyexploitfixes.cmd.say: true
      anarchyexploitfixes.cmd.help: true
      anarchyexploitfixes.cmd.disable: true
  anarchyexploitfixes.cmd.version:
    description: Show plugin version
  anarchyexploitfixes.cmd.reload:
    description: Reload plugin configuration
  anarchyexploitfixes.cmd.lag:
    description: Lag the server for testing purposes
  anarchyexploitfixes.cmd.geared:
    description: Show geared players
  anarchyexploitfixes.cmd.kickphrase:
    description: Kick players that have said certain phrases
  anarchyexploitfixes.cmd.elytra:
    description: Show players currently flying with elytra
  anarchyexploitfixes.cmd.say:
    description: Broadcast a message using your own prefix and format
  anarchyexploitfixes.cmd.disable:
    description: Disable aef via command for better plugman reload
  anarchyexploitfixes.cmd.toggleconnectionmsgs:
    description: Toggle connection messages
    default: not op
  anarchyexploitfixes.cmd.help:
    description: Shows a customizable help message to players
    default: not op